const words = [
    "The young entrepreneur spent several years learning about business, marketing, finance, and leadership before finally launching a company that solved a real problem for customers, and although the journey was filled with setbacks, failures, and moments of uncertainty, persistence eventually transformed a simple idea into a successful and growing organization.",

    "As the storm clouds gathered over the horizon and the wind began to sweep across the open fields, the villagers worked together to secure their homes, protect their livestock, and prepare for the heavy rain that weather forecasts had predicted for days, demonstrating how cooperation becomes especially valuable during difficult circumstances.",

    "Learning a new skill is rarely a straight path from beginner to expert because progress often arrives in small increments that are difficult to notice day by day, yet when people remain patient, continue practicing, and focus on consistent improvement rather than immediate perfection, remarkable growth eventually becomes visible.",

    "The library contained thousands of books covering subjects as diverse as science, history, philosophy, technology, literature, psychology, and art, allowing visitors to explore unfamiliar ideas, deepen their understanding of topics they already enjoyed, and discover perspectives that challenged their existing assumptions about the world.",

    "Modern technology has fundamentally changed the way people communicate, work, study, shop, and entertain themselves, creating opportunities that would have seemed impossible only a few decades ago, while also introducing new challenges related to privacy, attention, misinformation, and the increasing pace of daily life.",

    "During the long train journey across the country, passengers spent their time reading novels, listening to music, watching landscapes pass by the windows, sharing stories with strangers, and reflecting on future plans, turning what could have been a routine trip into a memorable and meaningful experience.",

    "Many athletes underestimate the importance of recovery, nutrition, hydration, and sleep because they focus primarily on training intensity, yet the ability to perform consistently at a high level often depends just as much on what happens outside the gym, field, track, or training facility as it does during workouts.",

    "The scientist carefully documented every observation, measurement, and unexpected result throughout the experiment because accurate records would later help identify patterns, verify conclusions, reproduce findings, and ensure that future researchers could build upon the knowledge generated by the study.",

    "As cities continue to expand and populations grow, urban planners must balance the need for housing, transportation, green spaces, environmental sustainability, economic development, and public services in ways that improve quality of life without sacrificing the long-term health of communities.",

    "Success is often portrayed as a dramatic breakthrough that occurs overnight, but in reality it is usually the result of hundreds or thousands of small decisions made consistently over long periods of time, each one contributing a tiny amount of progress that eventually accumulates into meaningful achievement.",

    "The experienced teacher understood that every student learned differently, so lessons were designed to include discussions, practical exercises, visual demonstrations, independent projects, and collaborative activities, ensuring that learners with different strengths could engage effectively with the material.",

    "When exploring a foreign country, travelers frequently discover that the most memorable experiences come not from famous landmarks or tourist attractions, but from ordinary conversations, unexpected encounters, local traditions, and small moments that reveal the unique character of a place and its people.",

    "Artificial intelligence is rapidly transforming industries ranging from healthcare and education to manufacturing and entertainment, enabling organizations to automate repetitive tasks, analyze vast amounts of data, improve decision making, and develop innovative products that were previously difficult or impossible to create.",

    "The mountain expedition required months of preparation, including physical conditioning, route planning, equipment testing, emergency training, and weather monitoring, because even a minor oversight could have serious consequences in such a demanding and unpredictable environment.",

    "Although failure can feel discouraging and frustrating in the moment, it often provides some of the most valuable lessons a person can receive because mistakes expose weaknesses, reveal blind spots, encourage adaptation, and create opportunities for improvement that success alone may never uncover.",

    "Throughout history, societies have advanced through the combined efforts of countless individuals whose contributions to science, medicine, engineering, agriculture, education, and culture helped improve living standards and expand humanity's collective understanding of the world.",

    "The software developer spent hours investigating a difficult bug that appeared only under very specific conditions, carefully examining logs, testing hypotheses, reviewing code changes, and recreating user behavior until the underlying cause was finally identified and corrected.",

    "A healthy lifestyle is not built through occasional bursts of motivation but through daily choices involving nutrition, exercise, sleep, stress management, and personal discipline, all of which interact over time to influence both physical well-being and long-term mental resilience.",

    "The orchestra performed with extraordinary precision as dozens of musicians coordinated their timing, dynamics, and expression, producing a rich and emotional sound that captivated the audience from the opening notes to the final applause at the end of the concert.",

    "People who develop strong critical thinking skills are generally better equipped to evaluate information, identify logical flaws, recognize misleading claims, weigh competing evidence, and make informed decisions in situations where the correct answer is not immediately obvious."
];

export function getRandomText() {
    return words[Math.floor(Math.random() * words.length)];
}